### ISSUE TITLE
[중요] 단지번호붙이기.py 파일 업로드 위치 변경으로 글 올립니다. (관리자분만 보시면 됩니다.)

### ISSUE THREAD

**Issue by gusdn3477** [Sejong-SWStudy/2021_SJU_BOJAlgorithm.py#101]
제가 어제 단지번호붙이기.py 파일을 그래프 폴더가 아닌, 메인 폴더에 업로드 해놔서, 
오늘 파일 위치를 제대로 하는 과정을 거쳤습니다.
여러 실수가 있긴 했는데, 결과적으로 잘 해결된 것 같습니다. 
아마 오늘 푼 시리얼번호.py가 merge 된 후에야 결과를 볼 수 있을 것 같습니다. (그 과정에서 커밋 기록이 처참하네요.)

혹여나 merge 과정에서 문제가 생길 수 있어 issue를 남깁니다. 제 파일을 마지막에 merge 하는 게 가장 안전할 것 같아요.
github를 더 공부하겠습니다. 죄송합니다.

**Comment by GHooN99** [comment]
확인하였슴다 괜찮아여 ㅎㅎ

**Comment by gusdn3477** [comment]
> 확인하였슴다 괜찮아여 ㅎㅎ

이슈 닫겠습니다!
